const data_mock = [
  {
      "_id": "a5a0bf1db63e4bef87940ff3af198072",
      "user_id": "388a467de34c4186a77e6f4b81abf1e0",
      "created_at": "1628505229.0669875",
      "updated_at": "1628505229.0669875",
      "title": "School",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
      "tags": "Sculptor",
      "processing_status": "processed",
      "post_image": "",
      "post_file": "https://s3.amazonaws.com/cohart.uploads-staging/D25B08A6-893A-44BB-B408-C04000C0F77E.mp4",
      "jw_media_id": "GdJ6V07U",
      "jw_media_url": "https://cdn.jwplayer.com/manifests/GdJ6V07U.m3u8",
      "jw_media_thumb": "https://cdn.jwplayer.com/v2/media/GdJ6V07U/poster.jpg?width=720",
      "post_type": "video",
      "is_hide": false,
      "created_by": {
        "_id": "388a467de34c4186a77e6f4b81abf1e0",
        "created_at": "1627625217.5429666",
        "updated_at": "1631527933.7903557",
        "appected_terms": "true",
        "phone_number": "+923002122131",
        "title_stamp": 3,
        "bio_view": true,
        "currently_view": true,
        "last_spotted_view": true,
        "portfolio_view": true,
        "post_view": true,
        "affliation_view": true,
        "sms_code": "907764",
        "sms_counter": 0,
        "sms_time": "1631527799.8121645",
        "community_channel": "",
        "is_live": false,
        "first_name": "Kendall warson",
        "full_name": "Kendall warson Warson",
        "last_name": "Warson",
        "user_country": "",
        "user_location": "Lahore ",
        "user_state": "",
        "user_interests": "Buying Artwork,Inspiration,Building My Community",
        "tutorial_view": true,
        "accepted_guideline": true,
        "background_image": "http://d1yzom3tpw7mrr.cloudfront.net/A242C87F-1ECC-49E9-9CC5-25183E4315B5.jpg",
        "cover_image": "http://d1yzom3tpw7mrr.cloudfront.net/8D027902-961C-48C4-995D-7E7D88F82855.jpg",
        "country": "",
        "location": "Lahore ",
        "state": "",
        "subtitle": "School",
        "tags": "Sculptor",
        "username": "Kendallwarson",
        "affiliations": "Test affiliations ",
        "bio": "Test bio",
        "currently": "Test currently ",
        "instagram": "Imrankhan ",
        "last_spotted": "Test last spotted ",
        "meet_me_at": "Test",
        "meet_me_at_view": true,
        "twitter": "ran",
        "website": "https:Twitter.com/",
        "last_active": 1631529753,
        "country_code": "+92",
        "user_number": "3002122131",
        "email": null,
        "by_pass_password": "123456",
        "by_pass_sms": false,
        "registration_id": "",
        "badge_count": 42,
        "is_hide": true,
        "is_admin": false
      },
      "glow_count": 2,
      "glow_by_current_user": false
    },
    {
      "_id": "1a0fba9e001b4128aa62bf7372fc9702",
      "user_id": "ef2bce59f8be48ef8b82eef7f2739de7",
      "created_at": "1629725432.1841385",
      "updated_at": "1633596770.6164856",
      "title": "Gallerist  artist collect",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
      "tags": "Artist,Painter,Sculptor,Gallerist",
      "processing_status": "processed",
      "post_image": "",
      "post_file": "https://s3.amazonaws.com/cohart.uploads-staging/2D6FB0B4-0A23-4EC2-9DDC-91EAA22A0E4F.mp4",
      "jw_media_id": "X4o1GlJC",
      "jw_media_url": "https://cdn.jwplayer.com/manifests/X4o1GlJC.m3u8",
      "jw_media_thumb": "https://cdn.jwplayer.com/v2/media/X4o1GlJC/poster.jpg?width=720",
      "post_type": "video",
      "is_hide": false,
      "created_by": {
          "_id": "ef2bce59f8be48ef8b82eef7f2739de7",
          "created_at": "1624889738.3366618",
          "updated_at": "1633500172.8130953",
          "appected_terms": "true",
          "phone_number": "+60123202777",
          "title_stamp": 3,
          "sms_code": "928609",
          "sms_counter": 0,
          "sms_time": "1633500151.6348424",
          "community_channel": "",
          "is_live": false,
          "first_name": "Shyevin",
          "full_name": "Shyevin S’ng",
          "last_name": "S’ng",
          "user_country": "",
          "user_location": "",
          "user_state": "",
          "user_interests": "Building My Community,Inspiration,Meeting  Artists",
          "tutorial_view": true,
          "accepted_guideline": true,
          "background_image": "http://d1yzom3tpw7mrr.cloudfront.net/CB63A561-0ED8-4892-A52F-A3B710A31EED.jpg",
          "cover_image": "http://d1yzom3tpw7mrr.cloudfront.net/ED22FF17-7901-4BC3-9771-8DFF717ADBC3.jpg",
          "country": "",
          "location": "HCMC",
          "state": "",
          "subtitle": "Gallerist  artist collect",
          "tags": "Artist,Painter,Sculptor,Gallerist",
          "username": "Shyevin",
          "affiliations": "",
          "affliation_view": true,
          "bio": "",
          "bio_view": true,
          "currently": "",
          "currently_view": true,
          "instagram": "",
          "last_spotted": "",
          "last_spotted_view": true,
          "meet_me_at": "",
          "meet_me_at_view": true,
          "portfolio_view": true,
          "post_view": true,
          "twitter": "",
          "website": "",
          "is_admin": true,
          "is_hide": false,
          "country_code": "+60",
          "email": "shyevin+1@cohart.co",
          "user_number": "123202777",
          "by_pass_password": "040504",
          "by_pass_sms": true,
          "registration_id": "",
          "last_active": 1633677402,
          "badge_count": 0
      },
      "glow_count": 1,
      "is_featured": true
  },
  {
      "_id": "79ecd8cffde74982ad5ad49c8574d9fc",
      "user_id": "ef2bce59f8be48ef8b82eef7f2739de7",
      "created_at": "1630310594.7429454",
      "updated_at": "1633596770.6164856",
      "title": "Gallerist  artist collect",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
      "tags": "Artist,Painter,Sculptor,Gallerist",
      "processing_status": "processed",
      "post_image": "",
      "post_file": "https://s3.amazonaws.com/cohart.uploads-staging/D027316A-5435-4B58-A543-0AACDA306DB4.mp4",
      "jw_media_id": "I07G3fLE",
      "jw_media_url": "https://cdn.jwplayer.com/manifests/I07G3fLE.m3u8",
      "jw_media_thumb": "https://cdn.jwplayer.com/v2/media/I07G3fLE/poster.jpg?width=720",
      "post_type": "video",
      "is_hide": false,
      "created_by": {
          "_id": "ef2bce59f8be48ef8b82eef7f2739de7",
          "created_at": "1624889738.3366618",
          "updated_at": "1633500172.8130953",
          "appected_terms": "true",
          "phone_number": "+60123202777",
          "title_stamp": 3,
          "sms_code": "928609",
          "sms_counter": 0,
          "sms_time": "1633500151.6348424",
          "community_channel": "",
          "is_live": false,
          "first_name": "Shyevin",
          "full_name": "Shyevin S’ng",
          "last_name": "S’ng",
          "user_country": "",
          "user_location": "",
          "user_state": "",
          "user_interests": "Building My Community,Inspiration,Meeting  Artists",
          "tutorial_view": true,
          "accepted_guideline": true,
          "background_image": "http://d1yzom3tpw7mrr.cloudfront.net/CB63A561-0ED8-4892-A52F-A3B710A31EED.jpg",
          "cover_image": "http://d1yzom3tpw7mrr.cloudfront.net/ED22FF17-7901-4BC3-9771-8DFF717ADBC3.jpg",
          "country": "",
          "location": "HCMC",
          "state": "",
          "subtitle": "Gallerist  artist collect",
          "tags": "Artist,Painter,Sculptor,Gallerist",
          "username": "Shyevin",
          "affiliations": "",
          "affliation_view": true,
          "bio": "",
          "bio_view": true,
          "currently": "",
          "currently_view": true,
          "instagram": "",
          "last_spotted": "",
          "last_spotted_view": true,
          "meet_me_at": "",
          "meet_me_at_view": true,
          "portfolio_view": true,
          "post_view": true,
          "twitter": "",
          "website": "",
          "is_admin": true,
          "is_hide": false,
          "country_code": "+60",
          "email": "shyevin+1@cohart.co",
          "user_number": "123202777",
          "by_pass_password": "040504",
          "by_pass_sms": true,
          "registration_id": "",
          "last_active": 1633677402,
          "badge_count": 0
      },
      "glow_count": 3,
      "is_featured": true
  },
  {
      "_id": "12ab5e08e23a4dea9d0ce78d15f2edc2",
      "user_id": "ef2bce59f8be48ef8b82eef7f2739de7",
      "created_at": "1627377233.348871",
      "updated_at": "1633596770.6164856",
      "title": "Gallerist  artist collect",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
      "tags": "Artist,Painter,Sculptor,Gallerist",
      "processing_status": "processed",
      "post_image": "",
      "post_file": "https://s3.amazonaws.com/cohart.uploads-staging/A56E0A39-2A16-4537-A7DE-21761649FCC4.mp4",
      "jw_media_id": "IWEUBfLF",
      "jw_media_url": "https://cdn.jwplayer.com/manifests/IWEUBfLF.m3u8",
      "jw_media_thumb": "https://cdn.jwplayer.com/v2/media/IWEUBfLF/poster.jpg?width=720",
      "post_type": "video",
      "is_hide": false,
      "created_by": {
          "_id": "ef2bce59f8be48ef8b82eef7f2739de7",
          "created_at": "1624889738.3366618",
          "updated_at": "1633500172.8130953",
          "appected_terms": "true",
          "phone_number": "+60123202777",
          "title_stamp": 3,
          "sms_code": "928609",
          "sms_counter": 0,
          "sms_time": "1633500151.6348424",
          "community_channel": "",
          "is_live": false,
          "first_name": "Shyevin",
          "full_name": "Shyevin S’ng",
          "last_name": "S’ng",
          "user_country": "",
          "user_location": "",
          "user_state": "",
          "user_interests": "Building My Community,Inspiration,Meeting  Artists",
          "tutorial_view": true,
          "accepted_guideline": true,
          "background_image": "http://d1yzom3tpw7mrr.cloudfront.net/CB63A561-0ED8-4892-A52F-A3B710A31EED.jpg",
          "cover_image": "http://d1yzom3tpw7mrr.cloudfront.net/ED22FF17-7901-4BC3-9771-8DFF717ADBC3.jpg",
          "country": "",
          "location": "HCMC",
          "state": "",
          "subtitle": "Gallerist  artist collect",
          "tags": "Artist,Painter,Sculptor,Gallerist",
          "username": "Shyevin",
          "affiliations": "",
          "affliation_view": true,
          "bio": "",
          "bio_view": true,
          "currently": "",
          "currently_view": true,
          "instagram": "",
          "last_spotted": "",
          "last_spotted_view": true,
          "meet_me_at": "",
          "meet_me_at_view": true,
          "portfolio_view": true,
          "post_view": true,
          "twitter": "",
          "website": "",
          "is_admin": true,
          "is_hide": false,
          "country_code": "+60",
          "email": "shyevin+1@cohart.co",
          "user_number": "123202777",
          "by_pass_password": "040504",
          "by_pass_sms": true,
          "registration_id": "",
          "last_active": 1633677402,
          "badge_count": 0
      },
      "glow_count": 0,
      "is_featured": true
  },
  {
      "_id": "9e0f2e641efd4f49b283fec6ba2c3a43",
      "user_id": "ef2bce59f8be48ef8b82eef7f2739de7",
      "created_at": "1627915431.4433103",
      "updated_at": "1633596770.6164856",
      "title": "Gallerist  artist collect",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
      "tags": "Artist,Painter,Sculptor,Gallerist",
      "processing_status": "processed",
      "post_image": "",
      "post_file": "https://s3.amazonaws.com/cohart.uploads-staging/0E3A950D-6E3D-4E20-93DB-938F2F671FFF.mp4",
      "jw_media_id": "ctyYewaa",
      "jw_media_url": "https://cdn.jwplayer.com/manifests/ctyYewaa.m3u8",
      "jw_media_thumb": "https://cdn.jwplayer.com/v2/media/ctyYewaa/poster.jpg?width=720",
      "post_type": "video",
      "is_hide": false,
      "created_by": {
          "_id": "ef2bce59f8be48ef8b82eef7f2739de7",
          "created_at": "1624889738.3366618",
          "updated_at": "1633500172.8130953",
          "appected_terms": "true",
          "phone_number": "+60123202777",
          "title_stamp": 3,
          "sms_code": "928609",
          "sms_counter": 0,
          "sms_time": "1633500151.6348424",
          "community_channel": "",
          "is_live": false,
          "first_name": "Shyevin",
          "full_name": "Shyevin S’ng",
          "last_name": "S’ng",
          "user_country": "",
          "user_location": "",
          "user_state": "",
          "user_interests": "Building My Community,Inspiration,Meeting  Artists",
          "tutorial_view": true,
          "accepted_guideline": true,
          "background_image": "http://d1yzom3tpw7mrr.cloudfront.net/CB63A561-0ED8-4892-A52F-A3B710A31EED.jpg",
          "cover_image": "http://d1yzom3tpw7mrr.cloudfront.net/ED22FF17-7901-4BC3-9771-8DFF717ADBC3.jpg",
          "country": "",
          "location": "HCMC",
          "state": "",
          "subtitle": "Gallerist  artist collect",
          "tags": "Artist,Painter,Sculptor,Gallerist",
          "username": "Shyevin",
          "affiliations": "",
          "affliation_view": true,
          "bio": "",
          "bio_view": true,
          "currently": "",
          "currently_view": true,
          "instagram": "",
          "last_spotted": "",
          "last_spotted_view": true,
          "meet_me_at": "",
          "meet_me_at_view": true,
          "portfolio_view": true,
          "post_view": true,
          "twitter": "",
          "website": "",
          "is_admin": true,
          "is_hide": false,
          "country_code": "+60",
          "email": "shyevin+1@cohart.co",
          "user_number": "123202777",
          "by_pass_password": "040504",
          "by_pass_sms": true,
          "registration_id": "",
          "last_active": 1633677402,
          "badge_count": 0
      },
      "glow_count": 0,
      "is_featured": true
  },
  {
      "_id": "cb22fe5ae1e64f38a5a60bf7a2a6171b",
      "user_id": "ef2bce59f8be48ef8b82eef7f2739de7",
      "created_at": "1626158057.279313",
      "updated_at": "1633596770.6164856",
      "title": "",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,",
      "tags": "",
      "processing_status": "processed",
      "post_image": "",
      "post_file": "http://cohart.uploads-staging.s3.amazonaws.com/3D21FB3C-ADFA-405E-A5EE-AC9986EF2D83.mp4",
      "jw_media_id": "mPszWqF7",
      "jw_media_url": "https://cdn.jwplayer.com/manifests/mPszWqF7.m3u8",
      "jw_media_thumb": "https://cdn.jwplayer.com/v2/media/mPszWqF7/poster.jpg?width=720",
      "post_type": "video",
      "is_hide": false,
      "created_by": {
          "_id": "ef2bce59f8be48ef8b82eef7f2739de7",
          "created_at": "1624889738.3366618",
          "updated_at": "1633500172.8130953",
          "appected_terms": "true",
          "phone_number": "+60123202777",
          "title_stamp": 3,
          "sms_code": "928609",
          "sms_counter": 0,
          "sms_time": "1633500151.6348424",
          "community_channel": "",
          "is_live": false,
          "first_name": "Shyevin",
          "full_name": "Shyevin S’ng",
          "last_name": "S’ng",
          "user_country": "",
          "user_location": "",
          "user_state": "",
          "user_interests": "Building My Community,Inspiration,Meeting  Artists",
          "tutorial_view": true,
          "accepted_guideline": true,
          "background_image": "http://d1yzom3tpw7mrr.cloudfront.net/CB63A561-0ED8-4892-A52F-A3B710A31EED.jpg",
          "cover_image": "http://d1yzom3tpw7mrr.cloudfront.net/ED22FF17-7901-4BC3-9771-8DFF717ADBC3.jpg",
          "country": "",
          "location": "HCMC",
          "state": "",
          "subtitle": "Gallerist  artist collect",
          "tags": "Artist,Painter,Sculptor,Gallerist",
          "username": "Shyevin",
          "affiliations": "",
          "affliation_view": true,
          "bio": "",
          "bio_view": true,
          "currently": "",
          "currently_view": true,
          "instagram": "",
          "last_spotted": "",
          "last_spotted_view": true,
          "meet_me_at": "",
          "meet_me_at_view": true,
          "portfolio_view": true,
          "post_view": true,
          "twitter": "",
          "website": "",
          "is_admin": true,
          "is_hide": false,
          "country_code": "+60",
          "email": "shyevin+1@cohart.co",
          "user_number": "123202777",
          "by_pass_password": "040504",
          "by_pass_sms": true,
          "registration_id": "",
          "last_active": 1633677402,
          "badge_count": 0
      },
      "glow_count": 0,
      "is_featured": true
  }
];


export { data_mock };