// loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

export const ENABLE_APP_LOADER = 'ENABLE_APP_LOADER';
export const DISABLE_APP_LOADER = 'DISABLE_App_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const PROFILE_DATA_REQUEST = 'PROFILE_DATA_REQUEST';
export const PROFILE_DATA_RESPONSE = 'PROFILE_DATA_RESPONSE';
export const USER_TOPICS_REQUEST = 'USER_TOPICS_REQUEST';
export const USER_TOPICS_RESPONSE = 'USER_TOPICS_RESPONSE';

export const REQUEST_OTP_WITH_USER_CODE_FOR_LOGIN = 'REQUEST_OTP_WITH_USER_CODE_FOR_LOGIN';
export const REQUEST_OTP_FOR_LOGIN = 'REQUEST_OTP_FOR_LOGIN';
export const REQUEST_RESEND_OTP = 'REQUEST_RESEND_OTP';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

export const REQUEST_GET_USER = 'REQUEST_GET_USER';
export const GET_USER_RESPONSE = 'GET_USER_RESPONSE';

export const ADD_NEW_POST_REQUEST = 'ADD_NEW_POST_REQUEST';
export const ADD_NEW_POST_RESPONSE = 'ADD_NEW_POST_RESPONSE';

export const UPDATE_PROFILE_DATA_REQUEST = 'UPDATE_PROFILE_DATA_REQUEST';
export const UPDATE_PROFILE_DATA_RESPONSE = 'UPDATE_PROFILE_DATA_RESPONSE';

export const SAVE_ART_WORK_DATA_REQUEST = 'SAVE_ART_WORK_DATA_REQUEST';
export const SAVE_ART_WORK_DATA_RESPONSE = 'SAVE_ART_WORK_DATA_RESPONSE';

export const UPDATE_USER_INFORMATION_REQUEST =
    'UPDATE_USER_INFORMATION_REQUEST';
export const UPDATE__USER_INFORMATION_RESPONSE =
    'UPDATE_USER_INFORMATION_RESPONSE';

export const ENABLE_SNACK_BAR = 'ENABLE_SNACK_BAR';
export const DISABLE_SNACK_BAR = 'DISABLE_SNACK_BAR';

export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';

export const GET_ALL_POST_REQUEST = 'GET_ALL_POST_REQUEST';
export const GET_ALL_POST_RESPONSE = 'GET_ALL_POST_RESPONSE';

export const START_DEEPLINK_REQUEST = 'START_DEEPLINK_REQUEST';
export const FINISH_DEEPLINK_REQUEST = 'FINISH_DEEPLINK_REQUEST';


export const GET_USER_POST_REQUEST = 'GET_USER_POST_REQUEST';
export const GET_USER_POST_RESPONSE = 'GET_USER_POST_RESPONSE';

export const GET_YOUR_CONNECTIONS_REQUEST = 'GET_YOUR_CONNECTIONS_REQUEST';
export const GET_YOUR_CONNECTIONS_RESPONSE = 'GET_YOUR_CONNECTIONS_RESPONSE';

export const GET_SUGGESTED_CONNECTIONS_REQUEST =
    'GET_SUGGESTED_CONNECTIONS_REQUEST';
export const GET_SUGGESTED_CONNECTIONS_RESPONSE =
    'GET_SUGGESTED_CONNECTIONS_RESPONSE';

export const GET_PENDING_REQUEST_REQUEST = 'GET_PENDING_REQUEST_REQUEST';
export const GET_PENDING_REQUEST_RESPONSE = 'GET_PENDING_REQUEST_RESPONSE';

export const GET_GROUP_FRIEND_REQUEST = 'GET_GROUP_FRIEND_REQUEST';
export const GET_GROUP_FRIEND_RESPONSE = 'GET_GROUP_FRIEND_RESPONSE';

export const GET_SUGGESTION_CATEGORIES_REQUEST =
    'GET_SUGGESTION_CATEGORIES_REQUEST';
export const GET_SUGGESTION_CATEGORIES_RESPONSE =
    'GET_SUGGESTION_CATEGORIES_RESPONSE';

export const FETCH_USER_WORK_REQUEST = 'FETCH_USER_WORK_REQUEST';
export const FETCH_USER_WORK_RESPONSE = 'FETCH_USER_WORK_RESPONSE';

export const GET_ACCEPT_PENDING_REQUEST_REQUEST =
    'GET_ACCEPT_PENDING_REQUEST_REQUEST';
export const REJECT_PENDING_REQUEST_REQUEST = 'REJECT_PENDING_REQUEST_REQUEST';
export const ADD_GROUP_REQUEST = 'ADD_GROUP_REQUEST';
export const ADD_GROUP_RESPONSE = 'ADD_GROUP_RESPONSE';

export const ADD_GROUP_USER_REQUEST = 'ADD_GROUP_USER_REQUEST';
export const ADD_GROUP_USER_RESPONSE = 'ADD_GROUP_USER_RESPONSE';

export const FETCH_GROUP_USER_REQUEST = 'FETCH_GROUP_USER_REQUEST';
export const FETCH_GROUP_USER_RESPONSE = 'FETCH_GROUP_USER_RESPONSE';

export const FETCH_USER_GROUP_REQUEST = 'FETCH_USER_GROUP_REQUEST';
export const FETCH_USER_GROUP_RESPONSE = 'FETCH_USER_GROUP_RESPONSE';

export const UPLOAD_BACKGROUND_IMAGE_REQUEST =
    'UPLOAD_BACKGROUND_IMAGE_REQUEST';
export const UPLOAD_BACKGROUND_IMAGE_RESPONSE =
    'UPLOAD_BACKGROUND_IMAGE_RESPONSE';

export const GET_MY_WORK_REQUEST = 'GET_MY_WORK_REQUEST';
export const GET_MY_WORK_RESPONSE = 'GET_MY_WORK_RESPONSE';

export const ACCEPT_COMMUNITY_GUIDE_LINES_REQUEST =
    'ACCEPT_COMMUNITY_GUIDE_LINES_REQUEST';
export const ACCEPT_COMMUNITY_GUIDE_LINES_RESPONSE =
    'ACCEPT_COMMUNITY_GUIDE_LINES_RESPONSE';
export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOGOUT = 'LOGOUT';

export const CLOSE_TUTORIAL = 'CLOSE_TUTORIAL';

export const CHANGE_NUMBER_REQUEST = 'CHANGE_NUMBER_REQUEST';
export const CHANGE_NUMBER_RESPONSE = 'CHANGE_NUMBER_RESPONSE';

export const VIEW_TUTORIAL_REQUEST = 'VIEW_TUTORIAL_REQUEST';
export const VIEW_TUTORIAL_RESPONSE = 'VIEW_TUTORIAL_RESPONSE';

export const TOGGLE_SOCKET_EVENT = 'TOGGLE_SOCKET_EVENT';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_USER_WORK_REQUEST = 'DELETE_USER_WORK_REQUEST';
export const LOGIN_AS_REQUEST = 'LOGIN_AS_REQUEST';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const LOG_OUT_API_LOADING = "LOG_OUT_API_CALLING";
