require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '11.0'

def make_target()
  permissions_path = '../node_modules/react-native-permissions/ios'
  config = use_native_modules!

  use_react_native!(
    path: config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    hermes_enabled: false
  )

  pod 'Permission-PhotoLibrary', path: "#{permissions_path}/PhotoLibrary"
  pod 'react-native-branch', path: '../node_modules/react-native-branch'

  pod 'JWPlayer-SDK', '~> 3.16.0'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!('Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3', 'Flipper' => '0.88.0')
  # use_flipper!('Flipper-Folly' => '2.6.7')

end

target 'cohart - beta' do
  make_target
end

target 'cohart' do
  make_target
  pod 'RNQrGenerator', :path => '../node_modules/rn-qr-generator'
  pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

end

post_install do |installer|
  react_native_post_install(installer)
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
    text = File.read(name)
    replace = text.gsub(findstr, replacestr)

    next unless text != replace

    puts 'Fix: ' + name
    system('chmod +w ' + name)
    File.open(name, 'w') { |file| file.puts replace }
    STDOUT.flush
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
