import { appFonts } from 'components/text';
import { iconColor, primary, textColor } from 'config/colors';
import { StyleSheet } from 'react-native';
import { heightPercentageToDP as hp, widthPercentageToDP as wp } from 'react-native-responsive-screen';

const styles = StyleSheet.create({
  container: {
    justifyContent: 'flex-end',
    flex: 1,
    alignItems: 'center',
    paddingBottom: hp(20),
  },
  checkContainer: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 23,
  },
  shortText: {
    width: 298.94,
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 18.0084,
    lineHeight: 22,
    alignItems: 'flex-end',
    textAlign: 'center',
    color: textColor,
    fontFamily: appFonts.InterRegular,
  },
  checkBox: {
    width: 20,
    height: 20,
    borderRadius: 5.7147,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0.476225,
    borderColor: iconColor,
    backgroundColor: textColor,
  },
  footer: {
    paddingLeft: 10,
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 17,
    color: textColor,
  },
  termsConditionLine: {
    paddingLeft: 3,
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 17,
    color: primary,
    textDecorationLine: 'underline',
    textDecorationColor: primary,
  },
  waitListButton: {
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 17,
    alignItems: 'center',
    textAlign: 'center',
    color: primary,
    paddingTop: 10,
  },
  referral: {
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 15.6501,
    lineHeight: 23,
    textAlign: 'center',
    color: primary,
    height: 23,
    marginTop: hp('11%'),
    textTransform: 'uppercase',
  },
  bottomText: {
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 10.955,
    lineHeight: 16,
    textTransform: 'uppercase',
    position: 'absolute',
    bottom: 10,
    left: 41.24,
    color: textColor,
  },
  imageBackground: {
    height: hp(100),
    width: wp(100),
  },
  loginButton: {
    marginTop: hp('3'),
    height: 48,
    borderRadius: 30,
    paddingLeft: 15,
    paddingRight: 15,
    backgroundColor: primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonTitle: {
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: wp('3.8'),

    textAlign: 'center',
    color: iconColor,
  },
});

export default styles;
