import { appFonts } from 'components/text';
import { iconColor, placeHolderColor, shimmerColor } from 'config/colors';
import { Platform, StyleSheet } from 'react-native';

import { textColor } from '../../config/colors';

const styles = StyleSheet.create({
  header: {
    height: 28.22,
    width: '100%',
    paddingLeft: 22.4,
    paddingRight: 22.4,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: 20,
  },
  descriptionView: {
    borderWidth: 1,
    borderColor: iconColor,
    borderRadius: 9,
    paddingLeft: 6,
    paddingRight: 6,
    paddingHorizontal: 17,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heading: {
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 22.0843,
    alignItems: 'center',
    textAlign: 'center',
    color: iconColor,
  },
  titleHeading: {
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: '500',
    marginLeft: 22.4,
    paddingRight: 22.4,
    fontSize: 35,
    width: '85%',
    height: 110,
    color: iconColor,
  },
  input: {
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: '500',
    marginLeft: 22.4,
    paddingRight: 22.4,
    fontSize: 35,
    width: '100%',
    height: 110,
    color: iconColor,
  },
  descriptionText: {
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 14,
    color: placeHolderColor,
    paddingLeft: 4,
  },
  footerView: {
    height: 350,
    width: '100%',
  },
  line: {
    width: 33.54,
    height: 3.59,
    alignSelf: 'center',
    backgroundColor: textColor,
    borderRadius: 5.98701,
  },
  footerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  footerContainer: {
    width: '100%',
    height: '100%',
    paddingHorizontal: 33,
    paddingTop: 20,
  },
  userView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  userAvatar: {
    width: 32.05,
    height: 32.05,
    borderRadius: 24.9131,
    backgroundColor: shimmerColor,
  },
  userName: {
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 14.0529,
    paddingLeft: 16.4,
  },
  footerText: {
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 11,
  },
  footerTextInput: {
    paddingTop: 0,
    fontSize: 10,
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    paddingLeft: 3,
    width: '60%',
    alignSelf: 'center',
    textAlignVertical: 'top',
  },
  descriptionTextInput: {
    fontSize: 10,
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    paddingLeft: 3,
    width: '100%',
    height: 125,
    textAlign: 'left',
    paddingTop: 20,
    textAlignVertical: 'top',
  },
  tag: {
    paddingLeft: 8,
    paddingRight: 8,
    borderRadius: 6.49051,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#000000',
  },
  tagText: {
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 10,
  },
  searchBarContainer: {
    marginTop: 22,
    paddingLeft: 29,
    paddingRight: 29,
    height: 40,
    flexDirection: 'row',
  },
  searchBar: {
    borderRadius: 10,
    flex: 1,
    height: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
    paddingRight: 10,
  },
  searchInput: {
    fontFamily: appFonts.InterRegular,
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 12,
    color: iconColor,
    height: 40,
    flex: 1,
  },
  bottomContainer: {
    flexDirection: 'row',
  },
  bottom: {
    flexDirection: 'row',
    width: '65%',
    height: 30,
  },
  switchContainer: {
    flexDirection: 'row',
    width: '45%',
  },
  switch: {
    transform: [{ scaleX: 0.5 }, { scaleY: 0.5 }],
    marginLeft: -10,
    marginTop: Platform.OS == 'ios' ? -8 : -10,
  },
  mediumHeading: { flexDirection: 'row', paddingTop: 5 },
  mediumView: { flexDirection: 'row', width: '65%' },
  priceView: { flexDirection: 'row', width: '45%' },
  descriptionTextView: {
    marginTop: 10,
    borderWidth: 0.5,
    borderColor: '#9D9D9D',
  },
  tagListView: { height: 30 },
});

export default styles;
