import { appFonts } from 'components/text';
import { iconColor, primary, textColor } from 'config/colors';
import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp } from 'react-native-responsive-screen';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: textColor,
    },
    communityHeader: {
        paddingTop: 20,

        justifyContent: 'space-between',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: wp(4),
    },
    searchIcon: {
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        paddingRight: 10,
    },
    headerView: { paddingHorizontal: 20 },
    bottomSheetContainer: {
        borderTopWidth: 3,
        borderTopColor: 'black',
        height: '100%',
        backgroundColor: textColor,
    },
    headerContainer: {
        borderBottomWidth: 0,
        alignItems: 'flex-start',
    },
    heading: {
        fontWeight: '500',
        paddingLeft: wp(4),
    },
    description: {
        fontSize: 12,
        paddingHorizontal: wp(4),
        fontFamily: appFonts.InterRegular,
        fontWeight: '400',
        paddingBottom: 10,
        color: iconColor,
        opacity: 0.5,
    },
    contentStyle: {
        paddingTop: 21.1,
        paddingHorizontal: wp('4%'),
        alignItems: 'center',
    },
    footer: {
        height: 50,
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatar: {
        height: wp('16%'),
        width: wp('16%'),
        borderWidth: 0,
        borderRadius: wp('9%'),
        paddingHorizontal: wp('3%'),
    },
    avatarImage: {
        height: wp('14%'),
        width: wp('14%'),
        borderWidth: 0,
        borderRadius: wp('7%'),
    },
    userContainer: { paddingLeft: 0,  borderWidth: 0 },
    searchBarStyle: { borderColor: iconColor, borderRadius: 15 },
    searchInputStyle: { fontSize: 15 },
    button: {
        borderColor: iconColor,
        borderWidth: 1,
        borderRadius: 20,
    },
    buttonText: {
        fontSize: 11,
        fontFamily: appFonts.InterRegular,
        fontWeight: '500',
        paddingVertical: 8,
        paddingHorizontal: 11,
        textTransform: 'uppercase',
    },
    friendContainer: {
        marginTop: 6,
        width: 56.4,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 12,
    },
    friendAvatarContainer: {
        width: 56.41,
        height: 56.41,
        borderRadius: 27,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.2,
        borderColor: '#0033f7',
    },
    notificationContainer: {
        position: 'absolute',
        width: 20,
        height: 20,
        right: 0,
        top: 0.23,
        borderRadius: 10,
        zIndex: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    connectionContainer: {
        backgroundColor: primary,
        marginTop: 26,
        paddingTop: 8,
        paddingBottom: 35,
    },
    mainHeading: {
        fontFamily: appFonts.InterRegular,
        fontStyle: 'normal',
        fontWeight: 'bold',
        fontSize: 40,
        color: iconColor,
    },
    connectionHeading: {
        paddingLeft: wp(4),
        fontFamily: appFonts.InterRegular,
        fontStyle: 'normal',
        fontWeight: 'bold',
        fontSize: 23.6594,
        lineHeight: 29,
        paddingBottom: 19.59,
        color: iconColor,
    },
    friendAvatarView: {
        width: 56.41,
        height: 56.41,
        borderRadius: 27,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.11871,
        borderColor: '#0033f7',
    },
    friendHeading: {
        fontFamily: appFonts.InterRegular,
        fontStyle: 'normal',
        fontWeight: 'normal',
        fontSize: 11.0379,
        textAlign: 'center',
        paddingTop: 3,
        color: iconColor,
    },
    friendListView: {
        width: '100%',
        paddingLeft: wp(4),
        flexWrap: 'wrap',
        flexDirection: 'row',
        marginTop: 19,
    },
    tagView: {
        borderRadius: 1000,
        marginLeft: 16,
        alignItems: 'center',
        paddingLeft: 5,
        paddingRight: 5,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#000000',
    },
    tag: {
        fontFamily: appFonts.InterRegular,
        fontStyle: 'normal',
        fontWeight: '800',
        fontSize: 11.04,
        textAlign: 'center',
        color: iconColor,
    },
    tagHeaderView: {
        // width: 24,
        height: 24,
        borderRadius: 12,
        paddingHorizontal: 7,
        alignItems: 'center',
        // justifyContent: 'center',
        borderWidth: 1,
        flexDirection: 'row',
        borderLeftColor: '#000000',
    },
});
export default styles;
